//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrainIMG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public long ID { get; set; }
        public int RecordID { get; set; }
        public Nullable<int> AlgoID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> LearningSize { get; set; }
        public string AlgoParam { get; set; }
        public Nullable<int> FeatureCount { get; set; }
        public Nullable<int> LearnDuration { get; set; }
        public Nullable<int> TestDuration { get; set; }
        public Nullable<int> TN { get; set; }
        public Nullable<int> FP { get; set; }
        public Nullable<int> FN { get; set; }
        public Nullable<int> TP { get; set; }
        public Nullable<double> NDS { get; set; }
        public Nullable<double> NTPR { get; set; }
        public Nullable<double> NTNR { get; set; }
        public Nullable<double> NPPV { get; set; }
        public Nullable<double> DiceScore { get; set; }
        public Nullable<double> PTPR { get; set; }
        public Nullable<double> PTNR { get; set; }
        public Nullable<double> PPPV { get; set; }
        public Nullable<double> Correctness { get; set; }
    
        public virtual TestRecord TestRecord { get; set; }
    }
}
